on:
  push:
    branches:
      - main
jobs:
  build-root-fs-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Get all of the versions of Python we care about
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: sudo apt install -y wget patchelf
      - run: wget https://github.com/animalize/pyzstd/archive/refs/tags/0.15.2.tar.gz

      - run: python3.8 ./build.py
      - run: python3.9 ./build.py
      - run: python3.10 ./build.py
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: |
            ./out/*
