on:
  push:
    branches:
      - main
jobs:
  build-root-fs-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Get all of the versions of Python we care about
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: sudo apt install -y wget build-essential
      - run: wget https://github.com/animalize/pyzstd/archive/refs/tags/0.15.2.tar.gz

      - run: python3.9 ./build.py
      - run: sudo apt install -y tree
      - run: tree .
